### ISSUE TITLE
Add an operator for BLEU metric as well as example for machine translation task

### ISSUE THREAD

**Issue by sourabhagr** [uptrain-ai/uptrain#278] opened 2023-06-27 17:38 UTC
BLEU is a metric commonly used in machine translation tasks. It compares the generated output with one or more reference translations and measures the similarity between them. 

BLEU scores range from 0 to 1, with higher scores indicating better performance.

**Comment by sky-2002** [comment] 2023-12-24 11:27
hey @sourabhagr , I can take this up, can you give any pointers on where to add this?

**Comment by ashish-1600** [comment] 2023-12-25 08:22
Hey @sky-2002 , Thanks for taking it up. Perhaps we can use nltk package for this metric. Check this [link](https://www.digitalocean.com/community/tutorials/bleu-score-in-python) for your reference. 

Please have a look at our rouge metric implementation [here](https://github.com/uptrain-ai/uptrain/blob/main/uptrain/operators/language/rouge.py). We can do the same for bleu metric as well.

**Comment by sky-2002** [comment] 2023-12-25 10:40
Almost done, jut that when I am testing it, there's some issue of `nltk`'s `blue_score` with `fractions.Fraction`, should we consider using `torchmetrics.text.BLEuScore`?

**Comment by ashish-1600** [comment] 2023-12-25 11:30
Sure @sky-2002 . We can go ahead with `torchmetrics.text.BLEuScore`

**Comment by sky-2002** [comment] 2023-12-25 11:33
Yeah, the issue is in file `nltk.translate.bleu_score.py` which in the `develop` branch has overloaded the `fractions.Fraction` class to accommodate the `_normalize` parameter. Whereas it is not yet released in the stable version via `pip` and thus raises error of `_normalize` not being parameter to the `__new__` function being called upon initialization. So we need to install from source using `pip install https://github.com/nltk/nltk/archive/develop.zip`

**Comment by sky-2002** [comment] 2023-12-25 12:24
I have created a PR, please tell me where and how to add the `torchmetrics` dependency, would do that.

**Closed** 2024-01-06 06:52 UTC
Labels: enhancement
